version: "3.8"

services:
  minio:
    image: minio/minio:RELEASE.2023-12-23T07-19-11Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server --address ":9000" --console-address ":9001" /data
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data

  spark:
    image: bitnami/spark:3.4.1
    container_name: spark
    environment:
      - SPARK_EXTRA_CLASSPATH=/opt/bitnami/spark/user-jars/*
      - SPARK_MODE=master
      - AWS_ACCESS_KEY_ID=minioadmin
      - AWS_SECRET_ACCESS_KEY=minioadmin
    ports:
      - "8080:8080"
      - "4040:4040"
    volumes:
      - ./app:/app
      - ~/jars:/opt/bitnami/spark/user-jars  # ⬅ Twoje własne biblioteki .jar idą tu
    depends_on:
      - minio

volumes:
  minio_data: